version: 2.1

working_dir: &working_dir /root/autopilot

executors:
  focal:
    docker:
      - image: ubuntu:20.04
    working_directory: *working_dir

jobs:
  build:
    executor: focal
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            apt update
            apt install -y --no-install-recommends ansible
      - run:
          name: Install dependencies
          command: ansible-playbook build/docker/playbook.yaml
      - run:
          name: Build
          command: |
            mkdir build_dir
            cd build_dir
            cmake ../
            make
            ./test --gtest_output=xml:test_output.xml
      - persist_to_workspace:
          root: /root/autopilot
          paths: build_dir

  test:
    executor: focal
    steps:
      - run:
          name: Install ca-certificates # this step is only needed because we are using a vanilla ubuntu image. see https://support.circleci.com/hc/en-us/articles/360016505753-Resolve-Certificate-Signed-By-Unknown-Authority-error-in-Alpine-images?flash_digest=39b76521a337cecacac0cc10cb28f3747bb5fc6a
          command: |
            apt update
            apt install -y --no-install-recommends ca-certificates
      - attach_workspace:
         at: /root/autopilot/build_dir
      - run:
          name: Run unit tests
          command: |
            cd build_dir
            pwd
            ls -alh
            cd build_dir
            pwd
            ls -alh
            ./test --gtest_output=xml:test_output.xml
      - store_test_results:
          path: build_dir

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
