version: 2.1

working_dir: &working_dir /root/autopilot

executors:
  focal:
    docker:
      - image: ubuntu:20.04
        working_director: *working_dir

jobs:
  build:
    executor: focal
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            apt update
            apt install -y --no-install-recommends ansible
      - run:
          name: Install dependencies
          command: ansible-playbook build/docker/playbook.yaml
      - run:
          name: Create build directory
          command: |
            mkdir build_dir
      - run:
          name: Build
          command: |
            cd build_dir
            cmake ../
            make
      - persist_to_workspace:
          root: /root/autopilot
          paths: build_dir

  test:
    executor: focal
    steps:
      - attach_workspace:
         at: /root/autopilot/build_dir
      - run:
          name: Run unit tests
          command: |
            cd build_dir
            ./test --gtest_output=xml:test_output.xml
      - store_test_results:
          path: build_dir

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
